### ISSUE TITLE
Example setup not working, tests failing

### ISSUE THREAD

**Issue by kubik369** [trojsten/django-tips#7]
- Pip installs django 2.x instead of the desired version
- example app requirements file refers to non-existing requirements file one level higher
- since we now have more experience, maybe we could make it run in docker?

**Comment by mhozza** [comment]
Urobil som to kompatibilne s Django 2 a dropol som oficialnu podporu python 2.
Co sa tyka dockera, myslim ze toto ma prilis jednoduchy setup na to aby bol docker overkill (zvlada pouziva dokonca sqlite). Doplnil som readme o dev setup.

Takze toto zatvaram.
